### ISSUE TITLE
i2c configuration mismatch and incorrect screenshot of hardware settings nfc module

### ISSUE THREAD

**Issue by rbr101** [luka6000/TagTuner#13]
Hi Luka,

Nice work you did here, just tested the configuration and now printing the case.
I love the concept of a physical disk togerther with musicassistent.

I had to change the ic2 config to get it working:
```
i2c:
  id: bus_i2c
  sda: 21
  scl: 22
  scan: False
  frequency: 100kHz
  timeout: 13ms #to prevent pn532 timeout
```

Changed to:

```
i2c:
  id: bus_i2c
  scan: False
  timeout: 13ms #to prevent pn532 timeout
```

The frequency part was failing the NFC module to load (Probably because i’m using a clone NFC). Also in the screenshots in the docu the jumper setting is wrong and should be the other way around. In the screenshots SPI is selected but should be i2c.

I also found some nice mini vinyl LP’s on ali that can be used:  https://nl.aliexpress.com/item/1005008275356934.html?spm=a2g0o.productlist.main.1.73bexpOFxpOFQO&algo_pvid=330ecaf5-44e4-499c-9cbc-2b31e3c44450&algo_exp_id=330ecaf5-44e4-499c-9cbc-2b31e3c44450-0&pdp_npi=4%40dis%21EUR%212.11%212.11%21%21%2115.62%2115.62%21%40211b816617365408249296785e8e5b%2112000044449056862%21sea%21NL%21831774388%21X&curPageLogUid=LxPuPhohACr4&utparam-url=scene%3Asearch%7Cquery_from%3A

My D1 esp32 does not have a green light ,  so i will probably add a ws2811 and a buzzer for feedback when writing /reading the tags.

Cheers!
